### PR TITLE
Full website

### PR DESCRIPTION
**Pull request by godiarksel**
Configure the full book collection application featuring three pages namely: 

1. The book list
2. The book details form
3. The contact section

This was achieved using Javascript, HTML and CSS.

### CODE REVIEW

**Review by Lameck1 — COMMENTED** [review]
Hi, @godiarksel, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

In this milestone, we expected to see collaboration between you and your coding partner. Since that's not evident, code review cannot commence on your PR until this collaboration issue is elevated to student success and addressed. I wish you all the best in resolving this.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**Please, remember to tag me in your question so I can receive the notification.**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by godiarksel** [comment]
The issue I am undergoing has been voiced to Student Success. It is unfortunate but this course of action had to be taken.

**Comment by uwadonat** [comment]
Hi @godiarksel, 

Thank you for your effort, unfortunately I cannot proceed to review your code until you get approval from success team.

kindly bear with us while we are waiting for their feedback.
## Invalid Code Review Request

You have submitted a project, that <EXPLAIN WHY PROJECT IS INVALID>

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

**Review by aimemalaika — APPROVED** [review]
Hi @godiarksel , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
